### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by songololo** [3drepo/assimp#6]
When attempting to build this version of assimp on ubuntu 14.04 I get this error:

```
/home/user/assimp/code/MultiPartOptim.cpp: In member function ‘void Assimp::MultiPartOptim::CountVer
ticesAndFaces(aiScene*, aiNode*, int, unsigned int, std::vector<unsigned int>&, std::vector<unsigned int>&, std
::vector<std::vector<std::vector<int> > >&, std::vector<std::vector<Assimp::splitMeshCount> >&)’:
/home/user/assimp/code/MultiPartOptim.cpp:158:15: warning: value computed is not used [-Wunused-valu
e]
    AI_SUCCESS == pcScene->mMaterials[pcMesh->mMaterialIndex]->Get(AI_MATKEY_OPACITY, opacity);
               ^
/home/user/assimp/code/MultiPartOptim.cpp: In member function ‘void Assimp::MultiPartOptim::CollectD
ata(aiScene*, aiNode*, int, unsigned int, aiMesh*, aiOptimMap*, unsigned int*, unsigned int*, const std::vector
<int>&, int&, aiNode*, bool&)’:
/home/user/assimp/code/MultiPartOptim.cpp:205:41: warning: comparison between signed and unsigned in
teger expressions [-Wsign-compare]
    if (splitListIDX == (splitList.size()))
                                         ^
/home/user/assimp/code/MultiPartOptim.cpp:210:52: warning: comparison between signed and unsigned in
teger expressions [-Wsign-compare]
    if (splitList[splitListIDX] == pcNode->mMeshes[i])
                                                    ^
/home/user/assimp/code/MultiPartOptim.cpp:402:38: warning: comparison between signed and unsigned in
teger expressions [-Wsign-compare]
   if (splitListIDX == splitList.size())
                                      ^
/home/user/assimp/code/MultiPartOptim.cpp: In member function ‘void Assimp::MultiPartOptim::GetVForm
atList(aiScene*, int, std::list<unsigned int>&)’:
/home/user/assimp/code/MultiPartOptim.cpp:427:24: warning: comparison between signed and unsigned in
teger expressions [-Wsign-compare]
    if (iMat == pcMesh->mMaterialIndex) {
                        ^
/home/user/assimp/code/MultiPartOptim.cpp: In member function ‘virtual void Assimp::MultiPartOptim::
Execute(aiScene*)’:
/home/user/assimp/code/MultiPartOptim.cpp:612:14: warning: value computed is not used [-Wunused-valu
e]
   AI_SUCCESS == pScene->mMaterials[i]->Get(AI_MATKEY_OPACITY, opacity);
              ^
/home/user/assimp/code/MultiPartOptim.cpp:638:49: error: in C++98 ‘iVertices’ must be initialized by
 constructor, not by ‘{...}’
   std::vector<unsigned int>  iVertices = { 0, 0 };
                                                 ^
/home/user/assimp/code/MultiPartOptim.cpp:639:46: error: in C++98 ‘iFaces’ must be initialized by co
nstructor, not by ‘{...}’
   std::vector<unsigned int>  iFaces = { 0, 0 };
                                              ^
/home/user/assimp/code/MultiPartOptim.cpp:647:16: warning: unused variable ‘processedFaces’ [-Wunuse
d-variable]
   unsigned int processedFaces    = 0;
                ^
/home/user/assimp/code/MultiPartOptim.cpp:715:47: error: in C++98 ‘iVertices’ must be initialized by
 constructor, not by ‘{...}’
     std::vector<unsigned int>  iVertices = { 0};
                                               ^
/home/user/assimp/code/MultiPartOptim.cpp:715:47: error: converting to ‘std::vector<unsigned int>’ f
rom initializer list would use explicit constructor ‘std::vector<_Tp, _Alloc>::vector(std::vector<_Tp, _Alloc>:
:size_type, const value_type&, const allocator_type&) [with _Tp = unsigned int; _Alloc = std::allocator<unsigne
d int>; std::vector<_Tp, _Alloc>::size_type = long unsigned int; std::vector<_Tp, _Alloc>::value_type = unsigne
d int; std::vector<_Tp, _Alloc>::allocator_type = std::allocator<unsigned int>]’
/home/user/assimp/code/MultiPartOptim.cpp:716:45: error: in C++98 ‘iFaces’ must be initialized by co
nstructor, not by ‘{...}’
     std::vector<unsigned int>  iFaces = { 0 };
                                             ^
/home/user/assimp/code/MultiPartOptim.cpp:716:45: error: converting to ‘std::vector<unsigned int>’ f
rom initializer list would use explicit constructor ‘std::vector<_Tp, _Alloc>::vector(std::vector<_Tp, _Alloc>:
:size_type, const value_type&, const allocator_type&) [with _Tp = unsigned int; _Alloc = std::allocator<unsigne
d int>; std::vector<_Tp, _Alloc>::size_type = long unsigned int; std::vector<_Tp, _Alloc>::value_type = unsigne
d int; std::vector<_Tp, _Alloc>::allocator_type = std::allocator<unsigned int>]’
/home/user/assimp/code/MultiPartOptim.cpp:894:90: warning: format not a string literal and no format
 arguments [-Wformat-security]
    pcNode->mName.length = ::sprintf(pcNode->mName.data, pScene->mLights[i]->mName.C_Str());
                                                                                          ^
/home/user/assimp/code/MultiPartOptim.cpp:901:91: warning: format not a string literal and no format
 arguments [-Wformat-security]
    pcNode->mName.length = ::sprintf(pcNode->mName.data, pScene->mCameras[i]->mName.C_Str());
                                                                                           ^
make[2]: *** [code/CMakeFiles/assimp.dir/MultiPartOptim.cpp.o] Error 1
make[1]: *** [code/CMakeFiles/assimp.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by henryliu-git** [comment]
I get the same error if I try to compile on Ubuntu 15.10 but if you checkout to commit e90fa501c7a8d5952ec1d72e858fd34f6d94ec57 then it should be fine. @carmenfan

**Comment by carmenfan** [comment]
This is due to c++11 reliance so if you compile it with a compiler with c++11 support and ensure you have the c11 flag in your cxx flag  it should be fine

This code is actually deprecated so if you feel brave you can just remove it

**Comment by songololo** [comment]
@thenrikie thanks, that got me further.

I am now running into a new issue to do with `gtest`:

```
[ 82%] Performing update step for 'gtest'
Already on 'master'
Your branch is up-to-date with 'origin/master'.
[ 83%] Performing configure step for 'gtest'
CMake Error at /home/user_home/assimp/build/test/gtest/src/gtest-stamp/gtest-configure.cmake:16 (message)
:
  Command failed: 1
   '/usr/bin/cmake' '-DCMAKE_BUILD_TYPE=' '-Dgtest_force_shared_crt=ON' '-Dgtest_disable_pthreads:BOOL=OFF' '-G
Unix Makefiles' '/home/user_home/assimp/build/test/gtest/src/gtest'
  See also
    /home/user_home/assimp/build/test/gtest/src/gtest-stamp/gtest-configure-*.log
make[2]: *** [test/gtest/src/gtest-stamp/gtest-configure] Error 1
make[1]: *** [test/CMakeFiles/gtest.dir/all] Error 2
make: *** [all] Error 2
```

The logfile states:

```
CMake Error: The source directory "/home/user_home/assimp/build/test/gtest/src/gtest" does not appear to contain CMakeLists.txt.
```

**Comment by carmenfan** [comment]
gtest is [googletest ](https://github.com/google/googletest)framework which is outside of our work in assimp. It looks like it's having problems compiling this. hard to tell what happened without seeing the log in /home/user_home/assimp/build/test/gtest/src/gtest-stamp/gtest-configure-*.log

You should only need this if you have a need to run the unit tests within ASSIMP. So if you don't intend to do any development work on ASSIMP, just disable the test builds by disabling the CMake flag, i.e.

```
cmake -DASSIMP_BUILD_TESTS=OFF .
```

**Comment by carmenfan** [comment]
see http://stackoverflow.com/questions/35219589/building-assimp-3-2-does-not-work-anymore 

We haven't merged latest from upstream master so I would suggest just disable the tests or change the link as instructed.

**Comment by songololo** [comment]
disabled the tests and now it works, thanks!
